### PR TITLE
Add logLik method

### LINKED ISSUE #6: Feature Request: logLik method?
Could you please include a `logLik()` method for `classIntervals` objects?  I took a first shot at one below, but it's not clear how to include a standard deviation when there is only one value in a group (or zero values in a group as can sometimes happen).  I'm sure that I'm missing more corner cases, and it wouldn't surprise me if it were more efficient to generate the likelihood immediately after the calculation (before returning the original object):

```r
logLik.classIntervals <- function(object, ...) {
  df <- length(object$brks) - 1
  current_loglik <- 0
  for (idx in seq_len(df)) {
    mask_current <-
      if (((idx == 1) & (attr(object, "intervalClosure") == "right")) |
          ((idx == df) & (attr(object, "intervalClosure") == "left"))) {
        object$brks[idx] <= object$var &
          object$var <= object$brks[idx + 1]
      } else if (attr(object, "intervalClosure") == "right") {
        object$brks[idx] < object$var &
          object$var <= object$brks[idx + 1]
      } else if (attr(object, "intervalClosure") == "left") {
        object$brks[idx] <= object$var &
          object$var < object$brks[idx + 1]
      }
    if (sum(mask_current)) {
      current_x <- object$var[mask_current]
      current_loglik <-
        current_loglik +
        if (length(unique(current_x)) == 1) {
          # Assume that the density is 1 at the unique value's location and zero
          # elsewhere.  Therefore the log-density is 0.
          0
        } else {
          sum(dnorm(x=current_x, mean=mean(current_x), sd=sd(current_x), log=TRUE))
        }
    }
  }
  structure(current_loglik, df=df, nobs=attr(object, "nobs"), class="logLik")
}
```

### PR DESCRIPTION
**Pull request by billdenney**
Fix #6, replaces #11

As I find roxygen easier to use and to ensure consistent documentation, I have created a new PR which strips that out but allows modification to the underlying roxygen code in the other branch.

### CODE REVIEW

**Comment by edzer** [comment]
I'd suggest to keep the roxygen in the source; if this package will make it for another 20+ years, at some stage somebody younger than all of us will have to take over maintenance, and may want to roxygenize the whole package...

**Comment by billdenney** [comment]
@edzer and @rsbivand, can you please resolve the preference between keeping or removing roxygen as I'm getting different preferences in your comments?

**Comment by edzer** [comment]
I let Roger decide.

**Comment by rsbivand** [comment]
Thanks for responding constructively. @edzer, do you have any students who might feel drawn to see whether cartographic subjective preferences match this measure, as an exercise? I don't mind roxygen as such, though I wouldn't write it myself. The roxygen source can stay in the R source file, provided that it doesn't disturb **pkgdown**, not checked yet. If it does, I guess it can be removed after merging. My I add @billdenney as contributor?

**Comment by billdenney** [comment]
I tried to reopen the PR with roxygen as they should otherwise be equal, but that didn't appear to work as expected, so I re-closed it.  I'll open a new roxygen-containing PR momentarily.

And, thanks for the acknowledgement as a contributor!  I'll open another PR for that (to try to avoid a spaghetti of PRs).

**Pull request closed without merging**
