### PR TITLE
Add "headtails" vignette

### LINKED ISSUE #20: New feature: "headtails" method
Hi, I included a new method on your package, named "headtails".  The method could be specially useful for highly-skewed data.

The idea behind that method is to get natural breaks by dividing all of the data values around the mean into two parts and continues the process iteratively for the values (above the mean) in the head until the head part values are not longer heavy-tailed distributed. By doing that, a thresold in terms of proportion of the values of the head is imposed (by default,  more than 40%).

The implementation is based on :
https://stackoverflow.com/questions/60062032/head-tail-breaks-classification-algorithm-in-r/60062737#60062737

that is a migration of the implementation on Phyton: https://github.com/chad-m/head_tail_breaks_algorithm/blob/master/htb.py

Full references:
Refs:
- Jiang, Bin (2013). "Head/tail breaks: A new classification scheme for data with a heavy-tailed distribution", The Professional Geographer, 65 (3), 482 – 494. https://arxiv.org/abs/1209.2801

- https://en.wikipedia.org/wiki/Head/tail_Breaks

I also modified `man` and included some examples.  My Travis Build status: 

[Build Status](https://travis-ci.org/dieghernan/classInt)

### PR DESCRIPTION
**Pull request by dieghernan**
Fix #20 This PR adds a vignette to the package. I used `knitr`, and also `rmarkdown`  has been added. The configuration was done by `usethis::use_vignette()` (https://usethis.r-lib.org/reference/use_vignette.html, @hadley).

Please let me know if this work matches your expectations.

A number of checks (not included in the PR) have been performed

- [x]  Installation on PC Windows 10, vignette works well
- [x]  Checked on travis (devel, release, oldrel), appveyor and `devtools::check()`, no fails
   - https://travis-ci.org/github/dieghernan/classInt/builds/667773863
   - https://ci.appveyor.com/project/dieghernan/classint
- [x]  Previews:
   - Rpubs: https://rpubs.com/dieghernan/headtailsvignette
   - pkgdown: https://dieghernan.github.io/classInt/articles/headtailsR.html

Regards

### CODE REVIEW

**Comment by dieghernan** [comment]
I forgot to add this, 
- The source package classInt_0.4-3.tar.gz is **136KB** on my computer.
- After installed, total size of the doc/ folder  is **256KB**

Regards

**Comment by rsbivand** [comment]
OK, thanks. Maybe the built size can be moderated by combining images, but this may be handled later when closer to CRAN submission.

**Comment by rsbivand** [comment]
Most of the added bulk is in the JS in the HTML file, I think. This is typical of rmarkdown, I'm afraid. Rendering to PDF with knit is about the same size. Since it is informative, I don't think it is a problem, but thanks for noticing and mentioning this.

**Comment by dieghernan** [comment]
Thank you, regards

**Comment by rsbivand** [comment]
**classInt** on CRAN, thanks very much for your contribution! We can refine the vignette later if need be.

**Comment by dieghernan** [comment]
My pleasure, thanks to you for all your contributions to the **R** community

**Comment by rsbivand** [comment]
... already deployed in **tmap** https://github.com/mtennekes/tmap/issues/406#issuecomment-610830460

**Pull request merged**
