### PR TITLE
add ctb

### PR DESCRIPTION
**Pull request by dieghernan**
Updated with ORCID

### CODE REVIEW

**Comment by rsbivand** [comment]
We'll see what CMD check says about the accent ...

**Comment by dieghernan** [comment]
Plz let me know, as with ORCID it is not a problem to switch to Hernangomez

**Comment by rsbivand** [comment]
Looks OK, maybe UTF-8 is accepted as ASCII now.

**Comment by dieghernan** [comment]
On Windows 10:

```
-- R CMD check results -------------------------------------------------- classInt 0.4-3 ----
Duration: 54.7s
```

Session info 

```r 
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] classInt_0.4-3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         compiler_3.5.1     prettyunits_1.1.1  remotes_2.1.0     
 [5] class_7.3-14       tools_3.5.1        testthat_2.3.1     digest_0.6.23     
 [9] packrat_0.5.0      pkgbuild_1.0.6     pkgload_1.0.2      memoise_1.1.0     
[13] rlang_0.4.4        cli_2.0.1          rstudioapi_0.10    xopen_1.0.0       
[17] e1071_1.7-3        withr_2.1.2        stringr_1.4.0      roxygen2_7.0.2    
[21] xml2_1.2.2         desc_1.2.0         fs_1.3.1           devtools_2.2.1    
[25] rprojroot_1.3-2    glue_1.3.1         R6_2.4.1           processx_3.4.1    
[29] fansi_0.4.1        rcmdcheck_1.3.3    sessioninfo_1.1.1  callr_3.4.1       
[33] purrr_0.3.3        magrittr_1.5       backports_1.1.5    ps_1.3.0          
[37] ellipsis_0.3.0     usethis_1.5.1      assertthat_0.2.1   KernSmooth_2.23-15
[41] stringi_1.4.5      crayon_1.3.4    
```

**Pull request merged**
